// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	publication "swc-api-back.com/internal/domain/model/publication"
)

// PublicationServiceMock is an autogenerated mock type for the Publication type
type PublicationServiceMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *PublicationServiceMock) Create(_a0 context.Context, _a1 publication.Publication) (publication.ID, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 publication.ID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, publication.Publication) (publication.ID, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, publication.Publication) publication.ID); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(publication.ID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, publication.Publication) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: _a0, _a1
func (_m *PublicationServiceMock) GetByID(_a0 context.Context, _a1 publication.ID) (publication.Publication, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 publication.Publication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, publication.ID) (publication.Publication, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, publication.ID) publication.Publication); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(publication.Publication)
	}

	if rf, ok := ret.Get(1).(func(context.Context, publication.ID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPublicationServiceMock creates a new instance of PublicationServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublicationServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PublicationServiceMock {
	mock := &PublicationServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
